### numpy + AutoGrad 

#### Tensor
- 다차원 Array를 표현하는 PyTorch 클래스
- Numpy의 ndarray와 동일
- Tensor 생성 함수도 거의 동일

#### torch.tensor(obj)
#### torch.FloatTensor(obj)
- array, ndarray, list를 Float형 tensor로 변환

In [12]:
import numpy as np
n_array = np.arange(10).reshape(2,5) 

#Float형 Tensor로 만드는 함수. aFloatTensor
t_array = torch.FloatTensor(n_array)
t_array2 = torch.FloatTensor([1,2,3,4])
print(t_array)
print(t_array2)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4.])


#### torch.from_numpy(ndarray)
- ndarray -> tensor 

## Numpy의 사용법이 그대로 적용됨
- slicing
- flatten()
- ones_like(object)
    - object와 같은 크기의 1로 이루어진 객체 생성
- shape
- dtype


Tensor.numpy()
   - tensor -> ndarray (numpy)

### linspace(start,end,n)
- 범위 내 균등한 간격의 n개의 값을 갖는 tensor 반환

In [18]:
torch.linspace(1,5,4) #4개 균일한 간격으로 생성

tensor([1.0000, 2.3333, 3.6667, 5.0000])

### GPU or CPU
- x_data.device
    - if cpu -> 'cpu'
    - if gpu -> 'cuda'

In [13]:
x_data.device

device(type='cpu')

In [17]:
from zoneinfo import available_timezones

#in colab
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
# x_data_cuda

NameError: name 'x_data_cuda' is not defined

### view
- numpy 의 reshape과 거의 동일
- view는 reshape된 형태만 보여줌 새로운 메모리에 저장하지 않음
- reshape은 메모리 구조가 깨지면 새로운 객체에 copy해서 보여줌
- view를 쓰면 됨.

In [18]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.8573, 0.1220],
         [0.7868, 0.2929],
         [0.9471, 0.8193]],

        [[0.8964, 0.9736],
         [0.8400, 0.7318],
         [0.6424, 0.6319]]])

In [32]:
# view, 형태를 바꿔서 보여줌
tensor_ex.view([-1,6])

tensor([[0.8573, 0.1220, 0.7868, 0.2929, 0.9471, 0.8193],
        [0.8964, 0.9736, 0.8400, 0.7318, 0.6424, 0.6319]])

In [37]:
# 메모리를 따로 할당하지 않음
a = torch.zeros(2,3)
b = a.view([-1,6])
a.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [38]:
# a에 1을 채웠는데 b도 1이 찼다. copy가 아님. 같은 메모리를 씀. 
b

tensor([[1., 1., 1., 1., 1., 1.]])

In [12]:
a=torch.zeros(3,2)
b=a.t().reshape(2,3)
c = a.t().reshape([-1,6])
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
a = a.t()
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
a.T

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [59]:
# reshape도 차원이 깨지지 않는이상 같은 메모리를 보여준다
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [61]:
# 데이터 구조가 깨지면 copy해서 새로운 객체로 보여준다. 
c

tensor([[0., 0., 0., 0., 0., 0.]])

### Tensor.clone().detach()
- Deepcopy
- .clone(): 내용을 복사한 텐서 생성(그러나 기존 tensor의 training graph 메모리에 존재)
- .detach() : Deeplearning training graph에서 벗어나 아예 따로 저장.

### 데이터 타입 변환 type
- Tensor = torch.type(Datatype)
datatype으로 바뀜

In [9]:
import torch
data1 = torch.zeros(2,dtype=torch.float) #32float
data2 = torch.ones(2,4, dtype=torch.double)
data3 = torch.rand(2,2,3,dtype=torch.half)
print(data1.dtype,data2.dtype,data3.dtype)

torch.float32 torch.float64 torch.float16


In [10]:
data1 = data1.type(torch.float32)
data2 = data2.type(torch.int)
data3 = data3.type(torch.double)
print(data1.dtype,data2.dtype,data3.dtype)


torch.float32 torch.int32 torch.float64


### size
- Tensor 의 axis별 크기 반환

In [8]:
import torch
data1= torch.DoubleTensor([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
    [10,11,12]]
])
print("data1's size:",data1.shape,'\n','axix 0 size:',data1.size(0),'\n','axis 1 size:',data1.size(1),'\n','axis 2 size:',data1.size(2))

data1's size: torch.Size([2, 2, 3]) 
 axix 0 size: 2 
 axis 1 size: 2 
 axis 2 size: 3


### squeeze
- 차원의 개수가 1인 차원을 삭제 (압축)

### tensor.unsqueeze(axis) or torch.unsqueeze(tensor,axis)
-  axis 방향으로 dim을 지정해서 해당 dim에 차원을 추가

In [2]:
import torch
tensor_ex = torch.rand(size=(2,1,2))
tensor_ex = tensor_ex.squeeze()
print(tensor_ex, tensor_ex.shape)

tensor([[0.7636, 0.6494],
        [0.3334, 0.1886]]) torch.Size([2, 2])


In [5]:
tensor_ex.unsqueeze(0).shape
print(tensor_ex.unsqueeze(0).shape,'\n', tensor_ex.unsqueeze(0))

torch.Size([1, 2, 2]) 
 tensor([[[0.7636, 0.6494],
         [0.3334, 0.1886]]])


In [4]:
tensor_ex.unsqueeze(1).shape
print(tensor_ex.unsqueeze(1).shape,'\n', tensor_ex.unsqueeze(1))

torch.Size([2, 1, 2]) 
 tensor([[[0.7636, 0.6494]],

        [[0.3334, 0.1886]]])


In [6]:
tensor_ex.unsqueeze(2).shape
print(tensor_ex.unsqueeze(2).shape,'\n', tensor_ex.unsqueeze(2))

torch.Size([2, 2, 1]) 
 tensor([[[0.7636],
         [0.6494]],

        [[0.3334],
         [0.1886]]])


## Tensor operations
- numpy와 거의 유사
- 차원이 다르면 개진다


행렬곱이란? 
- 수학시간의 행렬 곱
- vector 차원에서는 내적
- Not element wise operation

#### mm
- 행렬곱셈.(scalar, vector는 안됨)
- numpy는 dot이지만 Torch는 mm
- dot은 scalar나 vector일때만.

In [70]:
n2 = np.arange(10).reshape(5,2)
n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)
t1.mm(t2)



tensor([[ 60.,  70.],
        [160., 195.]])

In [71]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

### dot
- scalar, vector 내적 연산

In [80]:
t1 = t1.reshape(10)
t2 = t2.reshape(10)
t1.dot(t2)

tensor(285.)

### matmul
- shape이 맞을 때는 행렬내적
- shape이 안맞을 때는 broadcastind이 일어남
- ex. shape(5,2,3) matmul shape(3)
    - dim 0는 batch로 인식
    - batch 5 인 (2,3) matmul (3,1) 로 연산이 됨
    - 5개의 layer 마다 (2,3) mm (3,1) 하여 (5,2,1) shape의 값이 나옴.

In [82]:
# shape이 안맞아서 연산 불가
a = torch.rand(5,2,3)
b = torch.rand(3) # 크기 3의 벡터
a.mm(b)

RuntimeError: self must be a matrix

In [83]:
# 5 batch의 (2,3) 과 (3,1)의 mm으로 연산
a = torch.rand(5,2,3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.1071, 0.6791],
        [0.3910, 0.3060],
        [0.4981, 0.5321],
        [0.4815, 0.2422],
        [0.6298, 0.3041]])

In [92]:
# mm으로 표현하면 아래와 같다.
print(a[0].mm(torch.unsqueeze(b,1)))
print(a[1].mm(torch.unsqueeze(b,1)))
print(a[2].mm(torch.unsqueeze(b,1)))
print(a[3].mm(torch.unsqueeze(b,1)))
print(a[4].mm(torch.unsqueeze(b,1)))

tensor([[0.1071],
        [0.6791]])
tensor([[0.3910],
        [0.3060]])
tensor([[0.4981],
        [0.5321]])
tensor([[0.4815],
        [0.2422]])
tensor([[0.6298],
        [0.3041]])


### BroadCasting
- 사칙연산 중, Tensor 차원이 다를 경우 발생
- 차원이 달라도 각 차원의 원소 수는 같아야함
    - ex. (10,3,5) * (3,5)
- 서로 다른 차원의 원소가 없거나 1일 경우
    - (10,1,5) * (10,3,1)
    - (10,3,5) * (3,1)
    - (10,3,5) * (5)


### torch 통계값
- .min(), .max() : argment return
- .argmin(), .argmax() : index return
    - tensor를 1차원으로 풀었을 때의 index를 반환. 
    - tensor(n) 과 같이 tensor(int) 형태로 반환


## tensor save
 - torch.save(Tensor,'filename.pt')
 - Dict 형태로 여러개의 tensor 한번에 저장가능
    - 불러 올 때도 여러개 불러옴. 각 tensor의 이름으로 호출 가능

In [19]:
data1 = torch.linspace(1,5,4)
data2 = torch.linspace(1,10,4)
data3 = torch.linspace(1,100,4)
datas = {'data1':data1,'data2':data2,'data3':data3}
torch.save(datas,'mydata1.pt')

In [20]:
datas = torch.load('mydata1.pt')
datas['data1']

tensor([1.0000, 2.3333, 3.6667, 5.0000])

### nn.functional 모듈
- DL함수를 통해 다양한 수식 변환 지원
- nn.functional.softmax
- nn.functional.argmax -> nn.functional.one_hot()

#### one hot incoding example

In [96]:
import torch
import torch.nn.functional as F

n1 = torch.rand(3)
tensor  = torch.FloatTensor(n1)
h_tensor = F.softmax(tensor,dim = 0)
h_tensor



tensor([[0, 1, 2, 4, 4],
        [2, 2, 2, 2, 0],
        [3, 0, 2, 0, 4],
        [3, 4, 2, 4, 3],
        [1, 0, 3, 2, 2],
        [1, 4, 1, 0, 1],
        [2, 0, 1, 2, 3],
        [2, 0, 2, 3, 0],
        [3, 3, 0, 2, 3],
        [0, 1, 3, 4, 2]])

In [98]:
# 0~5 사이의 random int in shape of 10x5
y = torch.randint(5,(10,5))
# max arg's indexes in dim 1
y_lable = y.argmax(dim=1)
y_lable

tensor([3, 0, 2, 1, 2, 0, 4, 0, 1, 1])

In [99]:
# one hot 인코딩. target lable만 1 나머지는 0
# y 의 shape 정보가 남아있어서 10 by 5 형태로 출력해줌
F.one_hot(y_lable)

tensor([[0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]])

### AutoGrad
- 자동 미분지원
- backward 함수 사용
    - graph leaves에 대한 gradient를 계산함.

In [3]:
import torch
# 미분할 변수 대상에 requires_grad=True 해줌
# weight
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 10*y +25
# w에 관한 gradient 구함
z.backward()


None


In [8]:
# z에 관한 W의 gradient에, w값을 대입한 속성. 미분한 뒤 w 대입
w.grad

tensor(40.)

#### 편미분 autograd
- backward(gradient = tensor) 
- where tensor dim 크기: 미분할 변수 개수

In [113]:
a = torch.tensor([2.,3.], requires_grad= True)
b = torch.tensor([6.,4.], requires_grad= True)
Q = 3*a**3 - b**2
# 미분할 변수의 갯수 = external_grad 의 dim 크기
# external_grad = dQ/dQ, 즉 1 이어야 한다.
# 자기 자신에 대한 미분계수를 받으며 역전파(backward)시작하는 것 표현
external_grad = torch.tensor([1.,1])
Q.backward(gradient = external_grad)


In [109]:
# a 미분값
a.grad

tensor([ 36., 162.])

In [110]:
#b 미분값
b.grad

tensor([-12., -16.])

### extra_repr()
- To print customized extra information, you should re-implement this method in your own modules. Both single-line and multi-line strings are acceptable.
- module_repr로 모델출력했을 때, 모듈(extra repr) 처럼 추가 repr을 달고싶을 때 사용
- 모듈의 method로 넣어줘야함

In [ ]:
#example
class Function_A(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name
    def forward(self, x):
        x = x * 2
        return x

    def extra_repr(self):
        return 'name=duck'