### numpy + AutoGrad 

#### Tensor
- 다차원 Array를 표현하는 PyTorch 클래스
- Numpy의 ndarray와 동일
- Tensor 생성 함수도 거의 동일

In [2]:
import torch

data = [[3,5],[10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

#### tensor.FloatTensor(obj)
- array, ndarray, list를 Float형 tensor로 변환

In [12]:
import numpy as np
n_array = np.arange(10).reshape(2,5) 

#Float형 Tensor로 만드는 함수. aFloatTensor
t_array = torch.FloatTensor(n_array)
t_array2 = torch.FloatTensor([1,2,3,4])
print(t_array)
print(t_array2)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4.])
