# Numpy

### dtype , shape
- dtype: 데이터의 타입을 반환
    - np.array(a).dtype
- shape : array의 dimension을 튜플형태로 반환
    - np.array(a).shape
    - ex) array([1,2,3,4],dtype=int).shape = (4,) 4-coloumms
    - ex) array([[1,2,3,4],[5,6,7,8]],dtype=np.float64).shape = (2,4)
    - ex) 

### RANK
- shape의 차원의 수
    - 0 : scalar
        - 7
    - 1 : vector
        - [7,7]
    - 2 : matric    
        - [[10,10],[7,7]]
    - 3 : 3rd-order tensor
        - [[[1,1],[2,2]],[[3],[3]]]
    - n : n-th order tensor

### ndim
 - rank; number of dimensions

### size
- data의 개수

### nbytes
- ndarray object의 메모리 크기 반환
- ex) np.array([[1,2,3],[4,5,6]],dtype=np.float64).nbytes<br>
    = 6개의 32bit로 표현된 숫자 = 6개의 4byte숫자 = 24byte

## Numpy 와 행렬
- np.array([1,2,3]) 는 행 벡터이다. 가로로 긴.

### 행렬곱 matrix multiplication
 - 수학에서의 행렬 곱셈.
 - 연산 규칙: `MxN * NxA`
 - numpy 에서는 `@` 기호 사용. ex) `X @ Y`

    ##### 성분곱
    - 같은 인덱스 위치끼리 곱
    - 연산규칙 : `MxN * MxN`
    - 같은 크기의 행렬끼리 연산하여 같은 크기의 행렬 도출

### np.inner
 - np.inner Z의 (i,j)번째 성분은, X행렬의 i행벡터와 Y행렬의 j행벡터의 내적값.
 - 연산규칙 : `MxN * MxA`
 - `X @ Y.T` (Y transpose와 행렬곱)

### 유사역행렬 pseudo-inverse
- $A^{+}$ = $(A^{T}A)^{-1}A^{T}$ <font size =2>(행>= 열) </font>
    - $A^{+}A = I $
- $A^{+}$ = $A^{T}(AA^{T})^{-1}$ <font size =2>(행<= 열) </font>
    - $AA^{+} = I $
- Det(A) = 0 이어도 역행렬과 유사한 연산 수행
- numpy.linalg.pinv()

#### 역행렬
- nXn 함수이며, det가 0이 아닐경우 존재.
- np.linalg.inv()

In [2]:
import numpy as np

## Tranpose
- np.transpose(Data,axis)
- axis changing order를 정해줄 수 있음

In [30]:
a = np.arange(6).reshape(1,2,3)
a

array([[[0, 1, 2],
        [3, 4, 5]]])

In [31]:
b = a.transpose()
print(b.shape)
b

(3, 2, 1)


array([[[0],
        [3]],

       [[1],
        [4]],

       [[2],
        [5]]])

np.transpose(a, (1,2,0)) :
- dim0의 자리에 dim1 원소가 순서대로
- dim1의 자리에 dim2 원소가 순서대로

In [34]:
c = np.transpose(a,(1,2,0))
print(c.shape)
c

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

### reshape()

In [8]:
# 1. x = np.reshape(a,(n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = np.reshape(a,(2,3))
x


array([[ 1, 10,  2],
       [ 3,  4,  5]])

In [9]:
# 2. x = a.reshape((n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = a.reshape((2,3))
x


array([[ 1, 10,  2],
       [ 3,  4,  5]])

In [10]:
# 3. a.reshape(-1,n)
# shape에 -1이 들어간 경우, n으로 지정해준 축 만족시킨 후 가능한 차원으로 생성해준다.
a = np.array([1,10,2,3,4,5])
x = a.reshape((2,-1))
x


array([[ 1, 10,  2],
       [ 3,  4,  5]])

### flatten()
- 1차원 벡터로 바꿔줌

In [3]:
import numpy as np
a = np.array([[1,2,3],
             [1,2,3],
             [0,2,0]]).flatten()
a

array([1, 2, 3, 1, 2, 3, 0, 2, 0])

### Slicing
- 콤마 기준으로, 콤마 앞은 row 기준, 콤마 뒤는 column 기준으로 slice
- `,` 없으면 row 기준 slicing
- 0~n 로 indexing
- [0:n] $\rightarrow$ 1번째 데이터부터 n-1 번째 데이터
<br>
<br>
- 같은 row만 호출하더라도 vector일수도 matrix일수도 있음
    - array[1] : 벡터로 보여줌
    - array[1:3] : 한개의 row matrix로 보여줌 


In [19]:
# example
import numpy as np
a = np.array([[1,2,3],
             [4,5,6],
             [0,2,0]])
print(a[:,2:]) # 전체 열, 3행 전체
print('-----------')
print(a[1,1:3]) # 2번쨰 열, 2행~3행
print('-----------')
print(a[1:3])   # 2열~3열
print('-----------')

# 같은 data만 호출하더라도 의미가  다르다
print(a[2])     
print('-----------')
print(a[2:4])


[[3]
 [6]
 [0]]
-----------
[5 6]
-----------
[[4 5 6]
 [0 2 0]]
-----------
[0 2 0]
-----------
[[0 2 0]]


slicing 심화: step
- `arr[:,startpoint:endpoint:step]`
- `arr[startpoint:endpoint:step,:]`
- `arr[::2,::3]`
    - 첫열부터 한칸 씩 뛰고,
    - 첫행부터 두칸 씩 뛴 곳만 호출

#### 

# index 호출


#### `,` 기준으로 axis index로 접근
- matrix[axis0,axis1,axis2]
- matrix[axis0,axis1]
- matrix[axis0]

In [14]:
import numpy as np
a = np.array([[[1,1,1],
      [2,2,2]],
     [[3,3,3],
     [4,4,4]]])
a[1,0]

array([3, 3, 3])

In [15]:
a[1]

array([[3, 3, 3],
       [4, 4, 4]])

- np.argsort(a)
    - 작은 순서대로 index 반환

In [3]:
# np.argsort(a)
# 작은 순서대로 정렬시킨 후 index 반환

import numpy as np
a = np.array([[3,2,1],
             [4,5,6],
             [0,2,0]])
np.argsort(a[2,:])

array([0, 2, 1], dtype=int64)


### np.where(조건,if True arg, if False arg)
    - 조건을 만족하면 if True의 arg 가 호출, 안만족하면 if False의 arg 호출
    - if True, if False의 arg가 없을경우, 조건이 True인 element의 index 호출

In [8]:
# 1. np.where(a == 조건)
# array a 에서 조건에 해당하는 인자의 index를 array tuple로 반환 
# [0] 붙여줘야 array만 추출

import numpy as np
a = np.array([[3,2,1],
             [4,5,6],
             [0,2,0]])
print(a[0,:].argsort())
print(a[0,:].argsort()[0:1])
print(np.where(a[2,:] == a[0,:].argsort()[0:1][0])) # 3열에서, 값이 (a[0,:].argsort()[0:1][0]) 인 element의 index 가 모냐
print(np.where(a[2,:] == a[0,:].argsort()[0:1][0])[0])

[2 1 0]
[2]
(array([1], dtype=int64),)
[1]


In [13]:
# a에 대해, 3보다 작은 원소는 -1로 반환, 큰 원소는 1로 반환
np.where(a<3,-1,1)

array([[ 1, -1, -1],
       [ 1,  1,  1],
       [-1, -1, -1]])

### np.argmin(a, axis=), np.argmax(a, axis=)
    - 최소, 최고 element의 index 반환

In [33]:
# 2. np.argmin(a)
# array a의 최소 요소의 index 반환
# 자매품 np.argmax 도 있음
# axis = 0이면 axis = 0 를 따라 각 column의 min index 반환.
# axis = 1이면 axis = 1 를 따라 각 row의 min index 반환.
print(np.argmin(a,axis = 0),np.argmin(a,axis = 1))
print(np.argmax(a,axis = 0),np.argmax(a,axis = 1))


[2 0 2] [2 0 0]
[1 1 1] [0 2 1]


### boolean index
- 조건에 따른 boolean값을 array형태로 추출
- conditioning에 유용
    - 적용할 array와 shape이 같은 boolean array 사용 가능

In [10]:
import numpy as np
test_array = np.array([1,4,6,4,23,4,6], float)
print(test_array>3)
print(test_array[test_array > 3])


[False  True  True  True  True  True  True]
[ 4.  6.  4. 23.  4.  6.]


In [45]:
condition = test_array <3

test_array[condition]

array([1.])

In [40]:
# shape 같은 boolean array 생성
condition2 = np.array([True,True,False,False,False,False,False],bool)
test_array[condition2]

array([1., 4.])

### And : &, Or : |

In [12]:
print(test_array[(test_array>10)&(test_array<5)])
print(test_array[(test_array>10)|(test_array<5)])

[]
[ 1.  4.  4. 23.  4.]


### Fancy index
- int array를 index 값으로 활용
    - index로 사용할 array의 최대 element는 불러올 array의 len-1 이 최대
- take(a)를 사용할 수 있음


In [52]:
a = np.array([2,4,5,6],float)
b = np.array([1,2,3,2,1,2],int)
print(a[b])
print(a.take(b))


[4. 5. 6. 5. 4. 5.]
[4. 5. 6. 5. 4. 5.]


In [53]:
# matrix일 경우 두 index array의 같은 위치 element 쌍을 index로 받음
a = np.array([[1,4],[2,5],[3,5]],float)
b = np.array([1,1,1,0,0],int)
c = np.array([0,1,0,1,0],int)
# a의 (1,0),(1,1),(1,0),(0,1),(0,0) 가져옴
a[b,c]

array([2., 5., 2., 4., 1.])

In [54]:
# matrix 이면서 index array 하나만 넣으면 row 단위로 가져옴
a[b]

array([[2., 5.],
       [2., 5.],
       [2., 5.],
       [1., 4.],
       [1., 4.]])

----------------------------
### np.arange(start,end,step)


In [26]:
np.arange(0,30,3).reshape(-1,2)

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21],
       [24, 27]])

### np.zeros(shape,dtype,order)
- 0 채워줌
### np.ones(shape,dtype,order)
- 1 채워줌
### np.empty(shape,dtype,order)
- shape만 주어지고 비어있는 ndarray 생성
- 빈 공간 이전에 다른 프로그램이 썼던 값이 들어옴

__shape은 tuple로 넣어줌__

In [27]:
np.zeros((2,3),np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

### np.zeros_like(a)<br>np.ones_like(a)<br>np.empty_like(a)
- a와 같은 shape을 가져옴

### np.identity(n, dtype)
- 단위행렬 생성함

In [29]:
np.identity(3,np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

### np.eye( N = row개수,M = column개수,<br>K = 데이터 시작되는 column index)
- upper triangle 만든다


In [33]:
print(np.eye(3,5,k= 1))
print(np.eye(2,5,3))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.diag(matrix, k=start column index)
- matrix의 대각행렬을 추출함
- 참고. diagonal matrix는 대각선 빼고는 0인 행렬

In [36]:
matrix = np.arange(9).reshape(3,3)
print(np.diag(matrix))

print(np.diag(matrix,1))

[0 4 8]
[1 5]


### np.unique(array, return_counts = True)

In [14]:
# Unique 한 array 요소 반환
# return_counts = True -> unique 요소 array와 함께 각 요소의 개수 array 반환
a = np.array([1,2,3,3,3,3,4,4,4,4,2,2])
np.unique(a, return_counts = True) 


(array([1, 2, 3, 4]), array([1, 3, 4, 4], dtype=int64))

In [13]:
# 갯수, lable 쌍으로 배열하여 도출하기

# lable, 갯수 각각의 array로 반환.
lable , count = np.unique(a, return_counts = True) 
print(lable, count)

# zip을 통해 각 요소끼리 순차적으로 쌍으로 묶음.
print(dict(zip(lable,count))) #zip은 주소만 반환함.  dict 까지 해줘야 객체 반환.
b = dict(zip(lable,count))

# dict.items()를 통해 튜플 쌍으로 반환.
print(b.items())

# 배열
c = sorted(b.items(), key = lambda x:(-x[1],x[0])) #기본적으로 오름차순 배열
print(c)

[1 2 3 4] [1 3 4 4]
{1: 1, 2: 3, 3: 4, 4: 4}
dict_items([(1, 1), (2, 3), (3, 4), (4, 4)])
[(3, 4), (4, 4), (2, 3), (1, 1)]


### [:,None] , [:,np.newaxis] -- dimension 추가하기
#### (n,) -> (n,1) or (1,n)

In [67]:
# (n,)
a = np.array([1,2,3,3,3,3,4,4,4,4,2,2])
print(a.shape)

# row dim 추가
# (1,n)
# None 한 쪽에 dim 추가
c = a[None,:]
print(c.shape,'\n',c)

# column dim 추가 -> 하나의 row 형태인 array를 하나의 column 형태로 바꿈
# (n,1)
b = a[:,None]
print(b.shape,'\n',b)

# dimension 또 추가
# (n,1,1)
bb = b[:,None]
print(bb.shape,'\n',bb)

(12,)
(1, 12) 
 [[1 2 3 3 3 3 4 4 4 4 2 2]]
(12, 1) 
 [[1]
 [2]
 [3]
 [3]
 [3]
 [3]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]]
(12, 1, 1) 
 [[[1]]

 [[2]]

 [[3]]

 [[3]]

 [[3]]

 [[3]]

 [[4]]

 [[4]]

 [[4]]

 [[4]]

 [[2]]

 [[2]]]


------------------------------
## Numpy operation Functions
- axis : func operation의 기준
    -  axis = 0 : row를 따라서 연산.
    -  axis = 1 : column을 따라서 연산.

#### np.var(), np.std()

In [49]:
test_array = np.arange(1,11)
print(test_array.var())
print(test_array.std())

8.25
2.8722813232690143


### np.sum(axis,dtype)

In [56]:
test_array = np.arange(1,11).reshape(-1,2)
test_array.sum(axis=0),test_array.sum(axis=1)

(array([25, 30]), array([ 3,  7, 11, 15, 19]))

### Numpy 연산
- element wise mul, sum -> __very convenient__
- dot product
- __BROADCASTING 연산__
    -   다른 차원의 array간의 연산

In [70]:
# 연산 행렬 준비
a1 = np.array(range(12)).reshape(3,4)
a2 = -1*(np.array(range(12)).reshape(3,4))
aa1 = a1[0] # (n,)
aaa1 = aa1[:,None][:3]+1 #aa1[:,None].shape = (n,1). 열벡터로 만들어줌.
print('a1','\n',a1,'\n\n','a2','\n',a2,'\n\n','aa1','\n',aa1,'\n\n','aaa1','\n',aaa1,'\n\n')


a1 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 a2 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]] 

 aa1 
 [0 1 2 3] 

 aaa1 
 [[1]
 [2]
 [3]] 




In [72]:
# 행렬곱(element wise mul)

# 같은 차원
print('Same Dim','\n',a1*a2)
print()

# 다른 차원 (broadcasting 연산)
# elementwise 곱셈;. scalar를 elementwise 곱해줌
print('Different Dim','\n','0. 5 * (n,m)','\n',5*a1) 
print()
# row 단위의 element wise 곱
print('Different Dim','\n','1. (m,) * (n,m)','\n',aa1*a1) 
print()
# column 단위의 element wise 곱
print('2. (n,1) * (n,m)')
print(aaa1* a1)
print()
# element wise 곱
print('3. (1,n) * (n,1)')
print(aa1*aaa1)

Same Dim 
 [[   0   -1   -4   -9]
 [ -16  -25  -36  -49]
 [ -64  -81 -100 -121]]

Different Dim 
 0. 5 * (n,m) 
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Different Dim 
 1. (m,) * (n,m) 
 [[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]

2. (n,1) * (n,m)
[[ 0  1  2  3]
 [ 8 10 12 14]
 [24 27 30 33]]

3. (1,n) * (n,1)
[[0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [71]:
# 행렬 합(element wise sum)

# 같은 차원
print('Same Dim','\n',a1+a2)
print()

# 다른 차원
# element 단위의 덧셈. matrix 각각 element에 scalar 더해줌
print('Different Dim','\n','0. scalar + (n,m)','\n',5 + a1)
print()
# row 단위의 element wise 합. row 마다 더해줌
print('Different Dim','\n','1. (m,) + (n,m)','\n',aa1+a1) 
print()
# column 단위의 element wise 합, column 마다 더해줌
print('2. (n,1) + (n,m)')
print(aaa1 + a1)
print()
# element wise 합
print('3. (1,n) + (n,1)')
print(aa1+aaa1)

Same Dim 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Different Dim 
 0. scalar + (n,m) 
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Different Dim 
 1. (m,) + (n,m) 
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]

2. (n,1) + (n,m)
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]

3. (1,n) + (n,1)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [67]:
# dot product
# (n,m) * (m,n) 일때가능

a1.dot(a2.T)

array([[ -14,  -38,  -62],
       [ -38, -126, -214],
       [ -62, -214, -366]])

### np.linalg.norm(x, ord = None, axis = none, keepdims = False)
-   x : array
-   ord = -2, -1, 0 , 1, 2, 'fro' , 'nuc', np.inf, -np.inf<br><br>
    ord on _Matrices_
    - None = 'fro'
    - 'fro' = L2 distance
    - 'nuc' = sum of singular values
    - np.inf = max(sum(abs(x), axis = 1))   &nbsp;&emsp;&emsp;  row 별 절대값의 sum , 그중 최대 값 반환
    - -np.inf = min(sum(abs(x), axis = 1))  &emsp;&emsp; row 별 절대값의 sum , 그중 최소 값 반환
    - 0  없음
    - 1 = max(sum(abs(x), axis = 0))&nbsp;&emsp;&emsp;&emsp;&emsp; column 별 절대값의 sum , 그중 최대 값 반환
    - -1 = min(sum(abs(x), axis = 0))&emsp;&emsp;&emsp;&emsp; column 별 절대값의 sum , 그중 최소 값 반환
    - 2 = aka 2-norm,&nbsp; &emsp; &emsp; &emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp; largest singluar value 반환
    - -2 = smallest singular value 반환

    ord on _Vectors_
    - None = 2-norm, largest singular value
    - 'fro','nuc' 없음
    - np.inf = max(abs(x))&nbsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 최대 절대값 반환
    - -np.inf = min(abs(x))&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 최소 절대값 반환
    - 0 = sum(x!= 0)&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&emsp;&emsp;&nbsp; 0 아닌 value 합
    - ___1 = sum(abs(x))&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;L1 크기___&emsp;&emsp;&emsp;      sum(abs(x)`**`ord)`**`(1./ord) where ord = 1
    - -1 = sum(abs(x)`**`-1)**-1
    - ___2 = sum(abs(x)`**`2)`**`(1/2)&emsp;&emsp;&emsp;&emsp;&emsp;L2 크기___
    - -2 = sum(abs(x)`**`-2)`**`(1/-2)
<br><br>   
- keepsdime : 기준이 된 axis를 1로 남김
<br>
- axis : axis 별로 norm 계산함

### np.concatenate((array1,array2),axis)
    - array 합쳐서 array로 반환

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[7, 8], [9, 10], [11, 12]])

In [66]:
# 1. row 따라서 합치기
print(np.concatenate((a, b), axis=0),np.concatenate((a, b), axis=0).__dir__)


[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]] <built-in method __dir__ of numpy.ndarray object at 0x00000199B845FE70>


In [65]:
# 2. column 따라서 합치기
print(np.concatenate((a, b.T), axis=1))

[[ 1  2  7  9 11]
 [ 3  4  8 10 12]]


In [4]:
# 3. 한줄로 합치기
print(np.concatenate((a, b), axis=None))

[ 1  2  3  4  7  8  9 10 11 12]


### vstack, hstack
- `np.vstack((a,b))  (a,b는 array)`
    - axis = 0 로 concate
- `np.hstack((a,b))`
    - axis = 1 로 concate

In [63]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[7, 8], [9, 10], [11, 12]])

np.vstack((a,b)),np.hstack((a,b.T))

(array([[ 1,  2],
        [ 3,  4],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[ 1,  2,  7,  9, 11],
        [ 3,  4,  8, 10, 12]]))

### np.array.copy() : Deepcopy
 - copy module과는 다르게 np.array.copy()가 Deepcopy(새로운 객체생성)

 - shallow copy는 np.array.view()

### np.all(조건) , np.any(조건)
- 조건에 대해 True False 반환한다
- all : and 조건; 하나라도 false면 false
- any : or 조건; 하나라도 true면 true

- __조건이 없을경우 all True 인가? any True인가? 가 적용됨__

In [2]:
import numpy as np
a= np.arange(10)


np.any(a>5),np.all(a>0)

(True, False)

In [4]:
# 일반적인 비교.
# 각각 element에 대해 broadcasting 일어남
a > 5, a>0

(array([False, False, False, False, False, False,  True,  True,  True,
         True]),
 array([False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]))

### np.logical_and(a,b)<br> np.logical_not(a,b)<br> np.logical_or(a,b)
- a,b가 boolean일 경우, a와 b에 대한 and, not, or 조건을 적용함

In [25]:
print('AND condition = ',np.logical_and(a>5,a<3))
print('OR condition = ',np.logical_or(a>5,a<3))
print('NOT condition = ',np.logical_not(a>5))
# np.logical_and(a>5,a<3) 에 == true를 elementwise 적용한 뒤, 하나라도 True 면 True
print('ANY AND condition = ',np.any(np.logical_and(a>5,a<3) == True))
# np.logical_and(a>5,a<3) 에 == False를 elementwise 적용한 뒤, 모두 False 면 True
print('ALL AND condition = ',np.all(np.logical_and(a>5,a<3) == False))
# a>5 은 FFFFFFTTTT
# a<3 은 TTTFFFFFFF
#두 boolean을 And 조건 적용하면 all Fasle
#두 boolean을 OR 조건 적용하면 TTTFFFTTTT
#첫 번째 조건에 NOT 적용하면 TTTTTTFFFF

# True가 있는가? 
print('ANY AND condition2 = ',np.logical_and(a>5,a<3).any())
# 전부 True 인가?
print('ALL AND condition2 = ',np.logical_and(a>5,a<3).all())
# All False에 logical_not을 걸은 후, all true 인가?
print('ALL AND condition3 = ',np.logical_not(np.logical_and(a>5,a<3)).all())

AND condition =  [False False False False False False False False False False]
OR condition =  [ True  True  True False False False  True  True  True  True]
NOT condition =  [ True  True  True  True  True  True False False False False]
ANY AND condition =  False
ALL AND condition =  True
ANY AND condition2 =  False
ALL AND condition2 =  False
ALL AND condition3 =  True


### np.isnan(array)<br>np.isfinite(array)
- array의 elementwise nan/finite 여부를 boolean으로 반환
    - np.NaN == nan
    - np.Inf == infinite

# I/O

#### np.loadtext("주소",delimiter='\t')

#### np.savetxt("파일명",저장할 객체,fmt="%.2e",delimiter=',')
- fmt = 포멧, 소수점 두자리 까지

In [57]:
# array.astype(dtype)
# a의 타입을 int로
a_int = a.astype(int)

### np.save("파일명",arr = 객체)
- npy 파일로 객체를 저장함
- npy 파일은 pickle 형태

### test = np.load(file='')
- np 파일 불러와서 test 개체로 사용