In [1]:
import numpy as np

### reshape()

In [ ]:
# 1. x = np.reshape(a,(n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = np.reshape(a,(2,3))
x


In [ ]:
# 2. x = a.reshape((n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = a.reshape((2,3))
x


### index 호출

In [7]:
# 1. np.where(a == 조건)
# array a 에서 조건에 해당하는 인자의 index를 araray tuple로 반환 --> [0] 붙여줘야 array만 추출

import numpy as np
a = np.array([[1,2,3],
             [1,2,3],
             [0,2,0]])

print(np.where(a[2,:] == a[0,:].argsort()[0:1][0]),'\n',np.where(a[2,:] == a[0,:].argsort()[0:1][0])[0])

(array([0, 2], dtype=int64),) 
 [0 2]


In [13]:
# 2. np.argmin(a)
# array a의 초소 요소의 index 반환
# 자매품 np.argmax 도 있음
np.argmin(a[0,:])


1

In [ ]:
# 3. np.argsort(a)
# 작은 순서대로 정렬시킨 후 index 반환

np.argsort(a[2,:])

array([0, 2, 1], dtype=int64)

### np.unique(array, return_counts = True)

In [14]:
# Unique 한 array 요소 반환
# return_counts = True -> unique 요소 array와 함께 각 요소의 개수 array 반환
a = np.array([1,2,3,3,3,3,4,4,4,4,2,2])
np.unique(a, return_counts = True) 


(array([1, 2, 3, 4]), array([1, 3, 4, 4], dtype=int64))

In [13]:
# 갯수, lable 쌍으로 배열하여 도출하기

# lable, 갯수 각각의 array로 반환.
lable , count = np.unique(a, return_counts = True) 
print(lable, count)

# zip을 통해 각 요소끼리 순차적으로 쌍으로 묶음.
print(dict(zip(lable,count))) #zip은 주소만 반환함.  dict 까지 해줘야 객체 반환.
b = dict(zip(lable,count))

# dict.items()를 통해 튜플 쌍으로 반환.
print(b.items())

# 배열
c = sorted(b.items(), key = lambda x:(-x[1],x[0])) #기본적으로 오름차순 배열
print(c)

[1 2 3 4] [1 3 4 4]
{1: 1, 2: 3, 3: 4, 4: 4}
dict_items([(1, 1), (2, 3), (3, 4), (4, 4)])
[(3, 4), (4, 4), (2, 3), (1, 1)]
