In [2]:
import numpy as np

### reshape()

In [ ]:
# 1. x = np.reshape(a,(n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = np.reshape(a,(2,3))
x


In [ ]:
# 2. x = a.reshape((n, m))
# a를 nXm으로 reshape

a = np.array([1,10,2,3,4,5])
x = a.reshape((2,3))
x


### index 호출

In [7]:
# 1. np.where(a == 조건)
# array a 에서 조건에 해당하는 인자의 index를 araray tuple로 반환 --> [0] 붙여줘야 array만 추출

import numpy as np
a = np.array([[1,2,3],
             [1,2,3],
             [0,2,0]])

print(np.where(a[2,:] == a[0,:].argsort()[0:1][0]),'\n',np.where(a[2,:] == a[0,:].argsort()[0:1][0])[0])

(array([0, 2], dtype=int64),) 
 [0 2]


In [13]:
# 2. np.argmin(a)
# array a의 초소 요소의 index 반환
# 자매품 np.argmax 도 있음
np.argmin(a[0,:])


1

In [ ]:
# 3. np.argsort(a)
# 작은 순서대로 정렬시킨 후 index 반환

np.argsort(a[2,:])

array([0, 2, 1], dtype=int64)

### np.unique(array, return_counts = True)

In [14]:
# Unique 한 array 요소 반환
# return_counts = True -> unique 요소 array와 함께 각 요소의 개수 array 반환
a = np.array([1,2,3,3,3,3,4,4,4,4,2,2])
np.unique(a, return_counts = True) 


(array([1, 2, 3, 4]), array([1, 3, 4, 4], dtype=int64))

In [13]:
# 갯수, lable 쌍으로 배열하여 도출하기

# lable, 갯수 각각의 array로 반환.
lable , count = np.unique(a, return_counts = True) 
print(lable, count)

# zip을 통해 각 요소끼리 순차적으로 쌍으로 묶음.
print(dict(zip(lable,count))) #zip은 주소만 반환함.  dict 까지 해줘야 객체 반환.
b = dict(zip(lable,count))

# dict.items()를 통해 튜플 쌍으로 반환.
print(b.items())

# 배열
c = sorted(b.items(), key = lambda x:(-x[1],x[0])) #기본적으로 오름차순 배열
print(c)

[1 2 3 4] [1 3 4 4]
{1: 1, 2: 3, 3: 4, 4: 4}
dict_items([(1, 1), (2, 3), (3, 4), (4, 4)])
[(3, 4), (4, 4), (2, 3), (1, 1)]


### [:,None] , [:,np.newaxis] -- dimension 추가하기
#### (n,) -> (n,1) or (1,n)

In [14]:
# (n,)
a = np.array([1,2,3,3,3,3,4,4,4,4,2,2])
print(a.shape)

# row dim 추가
# (1,n)
c = a[None,:]
print(c.shape,'\n',c)

# column dim 추가 -> 하나의 row 형태인 array를 하나의 column 형태로 바꿈
# (n,1)
b = a[:,None]
print(b.shape,'\n',b)

# dimension 또 추가
# (n,1,1)
bb = b[:,None]
print(bb.shape,'\n',bb)

(12,)
(1, 12) 
 [[1 2 3 3 3 3 4 4 4 4 2 2]]
(12, 1) 
 [[1]
 [2]
 [3]
 [3]
 [3]
 [3]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]]
(12, 1, 1) 
 [[[1]]

 [[2]]

 [[3]]

 [[3]]

 [[3]]

 [[3]]

 [[4]]

 [[4]]

 [[4]]

 [[4]]

 [[2]]

 [[2]]]


### Numpy 연산
- element wise mul, sum -> __very convenient__
- dot product

In [58]:
a1 = np.array(range(12)).reshape(3,4)
a2 = -1*(np.array(range(12)).reshape(3,4))
aa1 = a1[0] # (n,)
aaa1 = aa1[:,None][:3]+1 #(n,1)
print('a1','\n',a1,'\n\n','a2','\n',a2,'\n\n','aa1','\n',aa1,'\n\n','aaa1','\n',aaa1,'\n\n')

a1 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 a2 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]] 

 aa1 
 [0 1 2 3] 

 aaa1 
 [[1]
 [2]
 [3]] 




In [64]:
# 행렬곱(element wise mul)

# 같은 차원
print('Same Dim','\n',a1*a2)
print()

# 다른 차원
# row 단위의 element wise 곱
print('Different Dim','\n','1. (n,) * (n,m)','\n',aa1*a1) 
print()
# column 단위의 element wise 곱
print('2. (n,1) * (n,m)')
print(aaa1* a1)
print()
# element wise 곱
print('3. (1,n) * (n,1)')
print(aa1*aaa1)

Same Dim 
 [[   0   -1   -4   -9]
 [ -16  -25  -36  -49]
 [ -64  -81 -100 -121]]

Different Dim 
 1. (n,) * (n,m) 
 [[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]

2. (n,1) * (n,m)
[[ 0  1  2  3]
 [ 8 10 12 14]
 [24 27 30 33]]

3. (1,n) * (n,1)
[[0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [65]:
# 행렬 합(element wise sum)

# 같은 차원
print('Same Dim','\n',a1+a2)
print()

# 다른 차원
# row 단위의 element wise 합
print('Different Dim','\n','1. (n,) + (n,m)','\n',aa1+a1) 
print()
# column 단위의 element wise 합
print('2. (n,1) + (n,m)')
print(aaa1 + a1)
print()
# element wise 합
print('3. (1,n) + (n,1)')
print(aa1+aaa1)

Same Dim 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Different Dim 
 1. (n,) + (n,m) 
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]

2. (n,1) + (n,m)
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]

3. (1,n) + (n,1)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [67]:
# dot product
# (n,m) * (m,n) 일때가능

a1.dot(a2.T)

array([[ -14,  -38,  -62],
       [ -38, -126, -214],
       [ -62, -214, -366]])

### np.linalg.norm(x, ord = None, axis = none, keepdims = False)
-   x : array
-   ord = -2, -1, 0 , 1, 2, 'fro' , 'nuc', np.inf, -np.inf<br><br>
    ord on _Matrices_
    - None = 'fro'
    - 'fro' = L2 distance
    - 'nuc' = sum of singular values
    - np.inf = max(sum(abs(x), axis = 1))   &nbsp;&emsp;&emsp;  row 별 절대값의 sum , 그중 최대 값 반환
    - -np.inf = min(sum(abs(x), axis = 1))  &emsp;&emsp; row 별 절대값의 sum , 그중 최소 값 반환
    - 0  없음
    - 1 = max(sum(abs(x), axis = 0))&nbsp;&emsp;&emsp;&emsp;&emsp; column 별 절대값의 sum , 그중 최대 값 반환
    - -1 = min(sum(abs(x), axis = 0))&emsp;&emsp;&emsp;&emsp; column 별 절대값의 sum , 그중 최소 값 반환
    - 2 = aka 2-norm,&nbsp; &emsp; &emsp; &emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp; largest singluar value 반환
    - -2 = smallest singular value 반환

    ord on _Vectors_
    - None = 2-norm, largest singular value
    - 'fro','nuc' 없음
    - np.inf = max(abs(x))&nbsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 최대 절대값 반환
    - -np.inf = min(abs(x))&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 최소 절대값 반환
    - 0 = sum(x!= 0)&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&emsp;&emsp;&nbsp; 0 아닌 value 합
    - ___1 = sum(abs(x))&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;L1 크기___&emsp;&emsp;&emsp;      sum(abs(x)`**`ord)`**`(1./ord) where ord = 1
    - -1 = sum(abs(x)`**`-1)**-1
    - ___2 = sum(abs(x)`**`2)`**`(1/2)&emsp;&emsp;&emsp;&emsp;&emsp;L2 크기___
    - -2 = sum(abs(x)`**`-2)`**`(1/-2)
<br><br>   
- keepsdime : 기준이 된 axis를 1로 남김
<br>
- axis : axis 별로 norm 계산함