### Random 모듈

In [3]:
import random

# 1. random.random() 
# 0~1 의 균일한 확률 분포에서 실수 난수 생성
random.random()

0.8395721113918798

In [5]:
# 2. seed
# 난수 생성의 기준 같은거

r_1 = 1 # seed 1
r_2 = 2 # seed 2

random.seed(r_1)
b_1 = random.random()
random.seed(r_1)      #같은 seed 에서 생성된 난수는 같다.
b_2 = random.random()
random.seed(r_2)
b_3 = random.random()

print(b_1,b_2,b_3)

0.13436424411240122 0.13436424411240122 0.9560342718892494


In [6]:
# 3. 범위 값 설정 후 랜덤 추출

# random.sample(range(p,q),r)
# p~ q-1 에서 r개 비복원 추출

random.sample(range(5,10),3)

[5, 9, 8]

### numpy 모듈

In [17]:
# random.rand() 
# 균일 분포

import numpy as np

# 1. np.random.rand()
# 0~1 사이 균일 확률 분포로 실수 난수 추출
a= np.random.rand()

# 2. np.random.rand(n)
# 0~1 사이 균등 확률 분포에서 n개 실수 배열 생성
b =np.random.rand(5)

# 3. np.random.rand(p,q)
# p ~ q-1 사이 균일 분포 난수를 PxQ matrix array로 생성
c =np.random.rand(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 0.21122763974555026 
 2.
  [0.99948903 0.96656159 0.83217963 0.06145886 0.99793419] 
 3.
  [[0.89516597 0.1708311  0.4512998 ]
 [0.09899183 0.04933619 0.76775646]
 [0.46208778 0.13396962 0.89887582]
 [0.05738096 0.04136156 0.85067845]
 [0.07330635 0.2008475  0.38796338]
 [0.4876755  0.94229925 0.37340957]
 [0.41329509 0.69611559 0.86338525]]


In [18]:
# random.randn()
# 가우시간 정규 분포 (m = 0, 표준편차 = 1)

# 1. np.random.randn()
# 0~1 사이 정규분포로 실수 난수 추출
a= np.random.randn()

# 2. np.random.randn(n)
# 0~1 사이 정규분포에서 n개 실수 배열 생성
b =np.random.randn(5)

# 3. np.random.randn(p,q)
# p ~ q-1 사이 정규 분포 난수를 PxQ matrix array로 생성
c =np.random.randn(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 1.1038432263684788 
 2.
  [-0.54312684 -0.01545701 -0.20715304 -3.01276657 -0.88235009] 
 3.
  [[ 0.10588854  0.09550656  1.67480338]
 [ 0.37780808  0.77391523  0.76819161]
 [ 1.19491854  0.08608634  0.89360739]
 [-0.25124158 -0.87966998 -0.64962233]
 [ 0.10506861  0.54094412  1.59786147]
 [ 0.16770715  2.37952667  1.17871398]
 [-0.75383435 -0.92008797 -0.2246122 ]]


In [31]:
# random.randint(n) 
# 정수 난수 출력
# randint() 은 무조건 하나 이상의 인수를 받아야함

# 1. np.random.randint(n)
# 0~ n-1 사이 정수에서 난수 1개 출력
a =np.random.randint(5)

# 2. np.random.randint(p,q) (p <= q)
# p ~ q-1 사이 정수에서 난수 하나 출력
b =np.random.randint(7,10)

# 3. np.random.random(p,q, size=m)
# p~ q-1 사이에서 m개 정수 list로 출력
c = np.random.randint(2,7,size=2)

print('1.\n',a,'\n','2.\n',b,'\n','3.\n',c)

1.
 3 
 2.
 7 
 3.
 [6 5]


In [ ]:
# np.random.choice(주머니,뽑을갯수,replace=True/False,p=p)
# replace = True : 복원추출, False: 비복원추출
# p : 원소별 뽑힐 확률