### Random 모듈

In [2]:
import random

In [3]:
# 1. random.random() 
# 0~1 의 균일한 확률 분포에서 실수 난수 생성
random.random()

0.8395721113918798

In [5]:
# 2. seed
# 난수 생성의 기준 같은거

r_1 = 1 # seed 1
r_2 = 2 # seed 2

random.seed(r_1)
b_1 = random.random()
random.seed(r_1)      #같은 seed 에서 생성된 난수는 같다.
b_2 = random.random()
random.seed(r_2)
b_3 = random.random()

print(b_1,b_2,b_3)

0.13436424411240122 0.13436424411240122 0.9560342718892494


In [6]:
# 3. 범위 값 설정 후 랜덤 추출

# random.sample(range(p,q),r)
# p~ q-1 에서 r개 비복원 추출

random.sample(range(5,10),3)

[5, 9, 8]

In [3]:
# 4. uniform(p,q)
# p~q 범위 사이의 실수 난수 생성

random.uniform(5,10)

7.193321090311155

### numpy 모듈

In [3]:
# random.rand() 
# 균일 분포

import numpy as np

# 1. np.random.rand()
# 0~1 사이 균일 확률 분포로 실수 난수 추출
a= np.random.rand()

# 2. np.random.rand(n)
# 0~1 사이 균등 확률 분포에서 n개 실수 배열 생성
b =np.random.rand(5)

# 3. np.random.rand(p,q)
# 균일 분포 난수를 PxQ matrix array로 생성
c =np.random.rand(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 0.9549939757559612 
 2.
  [0.41979964 0.03197976 0.30764627 0.08066553 0.73373807] 
 3.
  [[0.7463116  0.6666984  0.67081825]
 [0.13714327 0.05417113 0.51039395]
 [0.82482707 0.11502902 0.02244886]
 [0.34289483 0.3094831  0.12096931]
 [0.76447782 0.1202277  0.44691226]
 [0.83643297 0.17340701 0.90227371]
 [0.21713789 0.53915008 0.7842396 ]]


In [4]:
# random.randn()
# 가우시간 정규 분포 (m = 0, 표준편차 = 1)

# 1. np.random.randn()
# 0~1 사이 정규분포로 실수 난수 추출
a= np.random.randn()

# 2. np.random.randn(n)
# 0~1 사이 정규분포에서 n개 실수 배열 생성
b =np.random.randn(5)

# 3. np.random.randn(p,q)
# 정규 분포 난수를 PxQ matrix array로 생성
c =np.random.randn(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 -0.04269596702345541 
 2.
  [ 1.51543806  0.5138861  -0.83824335  0.98768009 -0.22154636] 
 3.
  [[ 0.20481923  1.70173745  0.19650909]
 [-2.61803807 -0.87730872 -0.19656549]
 [-0.09017576 -0.64763433 -0.02335893]
 [-0.05682159 -0.47885905  0.23204729]
 [ 0.06873607  1.22202493  0.18062824]
 [-0.70436482  1.95677412 -0.69120771]
 [-0.26557795 -1.49651252 -0.29076067]]


In [5]:
# 4. np.random.randn(p,q) < a
# a 보다 작은지 여부를 boolean 으로 반환.

c < 0.5

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [31]:
# random.randint(n) 
# 정수 난수 출력
# randint() 은 무조건 하나 이상의 인수를 받아야함

# 1. np.random.randint(n)
# 0~ n-1 사이 정수에서 난수 1개 출력
a =np.random.randint(5)

# 2. np.random.randint(p,q) (p <= q)
# p ~ q-1 사이 정수에서 난수 하나 출력
b =np.random.randint(7,10)

# 3. np.random.random(p,q, size=m)
# p~ q-1 사이에서 m개 정수 list로 출력 (복원추출)
c = np.random.randint(2,7,size=2)

print('1.\n',a,'\n','2.\n',b,'\n','3.\n',c)

1.
 3 
 2.
 7 
 3.
 [6 5]


In [ ]:
# np.random.choice(주머니,뽑을갯수,replace=True/False,p=p)
# replace = True : 복원추출, False: 비복원추출
# p : 원소별 뽑힐 확률