### Random 모듈

In [2]:
import random

In [3]:
# 1. random.random() 
# 0~1 의 균일한 확률 분포에서 실수 난수 생성
random.random()

0.8395721113918798

In [5]:
# 2. seed
# 난수 생성의 기준 같은거

r_1 = 1 # seed 1
r_2 = 2 # seed 2

random.seed(r_1)
b_1 = random.random()
random.seed(r_1)      #같은 seed 에서 생성된 난수는 같다.
b_2 = random.random()
random.seed(r_2)
b_3 = random.random()

print(b_1,b_2,b_3)

0.13436424411240122 0.13436424411240122 0.9560342718892494


In [6]:
# 3. random.sample(range(p,q),r)

# 범위 값 설정 후 랜덤 추출
# p~ q-1 에서 r개 비복원 추출

random.sample(range(5,10),3)

[5, 9, 8]

In [34]:
# 4. random.uniform(p,q) (p<=q)
# p~q 범위 사이의 실수 난수 생성

random.uniform(5,5)

5.0

In [36]:
# 5. random.randint(p,q) (p<=q)
# p~q 사이의 정수 난수 생성

random.randint(3,3)

3

### numpy 모듈

In [9]:
# np.random.rand() 
# 균일 분포

import numpy as np

# 1. np.random.rand()
# 0~1 사이 균일 확률 분포로 실수 난수 추출
a= np.random.rand()

# 2. np.random.rand(n)
# 0~1 사이 균등 확률 분포에서 n개 실수 배열 생성
b =np.random.rand(5)

# 3. np.random.rand(p,q)
# 균일 분포 난수를 PxQ matrix array로 생성
c =np.random.rand(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 0.6790715951863021 
 2.
  [0.69830418 0.13613212 0.9489068  0.22504431 0.70419769] 
 3.
  [[0.62077512 0.67194107 0.30201155]
 [0.18542474 0.08926132 0.95001862]
 [0.48638095 0.72282918 0.97375615]
 [0.95806551 0.08896726 0.50138577]
 [0.63223348 0.1962452  0.34412725]
 [0.58408783 0.90823247 0.53817961]
 [0.5590369  0.57828631 0.19320997]]


In [4]:
# np.random.randn()
# 가우시간 정규 분포 (m = 0, 표준편차 = 1)

# 1. np.random.randn()
# 0~1 사이 정규분포로 실수 난수 추출
a= np.random.randn()

# 2. np.random.randn(n)
# 0~1 사이 정규분포에서 n개 실수 배열 생성
b =np.random.randn(5)

# 3. np.random.randn(p,q)
# 정규 분포 난수를 PxQ matrix array로 생성
c =np.random.randn(7,3)

print('1.\n',a,'\n','2.\n ',b,'\n','3.\n ',c)

1.
 -0.04269596702345541 
 2.
  [ 1.51543806  0.5138861  -0.83824335  0.98768009 -0.22154636] 
 3.
  [[ 0.20481923  1.70173745  0.19650909]
 [-2.61803807 -0.87730872 -0.19656549]
 [-0.09017576 -0.64763433 -0.02335893]
 [-0.05682159 -0.47885905  0.23204729]
 [ 0.06873607  1.22202493  0.18062824]
 [-0.70436482  1.95677412 -0.69120771]
 [-0.26557795 -1.49651252 -0.29076067]]


In [5]:
# 4. np.random.randn(p,q) < a
# a 보다 작은지 여부를 boolean 으로 반환.

c < 0.5

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [31]:
# np.random.randint(n) 
# 정수 난수 출력
# randint() 은 무조건 하나 이상의 인수를 받아야함

# 1. np.random.randint(n)
# 0~ n-1 사이 정수에서 난수 1개 출력
a =np.random.randint(5)

# 2. np.random.randint(p,q) (p < q)    numpy.random과 일반 random 모듈의 차이. 일반 모듈은 p <= q
# p ~ q-1 사이 정수에서 난수 하나 출력
b =np.random.randint(1,2)

# 3. np.random.random(p,q, size=m)
# p~ q-1 사이에서 m개 정수 list로 출력 (복원추출)
c = np.random.randint(2,7,size=2)

print('1.\n',a,'\n','2.\n',b,'\n','3.\n',c)

1.
 1 
 2.
 1 
 3.
 [6 3]


In [ ]:
# np.random.choice(주머니,뽑을갯수,replace=True/False,p=p)
# replace = True : 복원추출, False: 비복원추출
# p : 원소별 뽑힐 확률